version: '3'
services:
  app:
    build: .

#  pgadmin:
#    container_name: pgadmin4_container
#    image: dpage/pgadmin4
#    tty: true
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: root
#    ports:
#      - "9000:80"