basePath: /
definitions:
  balance_handlers.Input:
    properties:
      quantity:
        type: integer
    type: object
  balance_handlers.Response:
    properties:
      data: {}
      status:
        type: string
      statusCode:
        type: integer
    type: object
  stock_handlers.Response:
    properties:
      data: {}
      status:
        type: string
      statusCode:
        type: integer
    type: object
  usecase.CreateProductInput:
    properties:
      creation_date:
        type: string
      expiration_date:
        type: string
      name:
        type: string
      quantity:
        type: integer
    type: object
  usecase.GetProductOutput:
    properties:
      creation_date:
        type: string
      expiration_date:
        type: string
      id:
        type: string
      name:
        type: string
      quantity:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: allan.cordeiro.santos@gmail.com
    name: Allan Cordeiro
    url: http://www.allancordeiro.com
  description: Product API with stock management
  termsOfService: http://www.swagger.io/terms
  title: Despensa Faculdade Impacta's Project
  version: "1.0"
paths:
  /api/products/{productID}/decrease:
    post:
      consumes:
      - application/json
      description: Create product stock transactions
      parameters:
      - description: product decrease amount
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/balance_handlers.Input'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/balance_handlers.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/balance_handlers.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/balance_handlers.Response'
      summary: Create Product Balance
      tags:
      - products
  /api/stock:
    get:
      description: Get the list of all available products
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/usecase.GetProductOutput'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/stock_handlers.Response'
      summary: Get Products list
      tags:
      - stock
    post:
      consumes:
      - application/json
      description: Create a new product and merge it to stock
      parameters:
      - description: product information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/usecase.CreateProductInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/stock_handlers.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/stock_handlers.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/stock_handlers.Response'
      summary: Create Product
      tags:
      - stock
swagger: "2.0"
