# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
# this workflow has been changed do consider only backend folder and its subfolders.

name: Go

on:
  push:
    branches: [ "Main" ]
    paths:
      - "backend/**"
  pull_request:
    branches: [ "Main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Test
      run: go test -v ./...
